DELETE { graph ?g { ?s <https://braine.eccenca.dev/vocabulary/itops#hasImageState> ?o } }
INSERT { graph ?g { ?s <https://braine.eccenca.dev/vocabulary/itops#hasImageState> <{state}> } }
WHERE {  
  graph ?g { 
    ?s ?p ?o .
  filter(?s = <{id}>)
}}