# Relay configuration
origin: kubernetes # origin 'kubernetes' (using default kubernetes configuraion) or 'kafka'
kind: node # 'node' or 'pod'
# pod.namespace: default # only possible for kind 'pod'
version: v1beta1 # api version current supports only 'v1beta1'
interval: 2 # interval in seconds
mode: async # broadcasting can be in 'sync' (default) or 'async' modes
out: # available options 'stdout' and 'cmem'
  - stdout # output to stdout
  - cmem # output to cmem
group: metrics.k8s.io # group, use 'metrics.k8s.io' for metrics server

# kafka configuration
# kafka.host: localhost:9092 # (default kafka host)
# kafka.topic: k8s.mtrics.nodes # default topic

# K8s configuration (use only when 'origin:kubernetes', default configuration loaded from config.load_kube_config())
# kubernetes.host: http://localhost:8080
# kubernetes.key : ?

# CMEM configuration
cmem.update.graph: https://vocab.eccenca.com/itops/kubernetes # target GRAPH
cmem.node.template: node.template.nt # node template triples
cmem.pod.template: pod.template.nt # pod template triples
cmem.update.template: query.update.template.sparql # SPARQL insert template
