# Relay configuration
origin: kubernetes # origin 'kubernetes' (using default kubernetes configuraion) or 'kafka'
kind: node
# pod.namespace: default # only possible for kind 'pod'
version: v1beta1 # api version current supports only 'v1beta1'
interval: 30 # interval in seconds
mode: async # broadcasting can be in 'sync' (default) or 'async' modes
out: # available options 'stdout' and 'cmem'
  - stdout # output to stdout
  - cmem # output to cmem
group: metrics.k8s.io # group, use 'metrics.k8s.io' for metrics server

# CMEM configuration
cemc.update.graph: https://vocab.eccenca.com/itops/kubernetes # target GRAPH
cmemc.node.template: node.template.nt # node template triples
cmemc.pod.template: pod.template.nt # pod template triples
cemc.update.template: cmem.update.tempalte.sparql # SPARQL insert template
